---
title: "Principal Component Analysis"
author: "Xiaochi"
date: "01/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(FactoMineR)
library(factoextra)
library(ggpubr)
```

# All Samples


```{r}
df_vege <- read_rds("../data_output/df_vege.rds")
res.pca <- PCA(df_vege[ , c("As", "Cd", "Cr", "Cu", "Mn", "Pb", "Ni", "Zn")], 
               graph = FALSE)
```

## Eigenvalues / Varianaces


```{r}
eig.val <- get_eigenvalue(res.pca)
```


```{r}
fviz_eig(res.pca, addlabels = TRUE, title = "Scree Plot") +
  theme_classic2()
```

## Graph of individuals

```{r}
fviz_pca_ind(res.pca,
             geom.ind = "point", # show points only (but not "text")
             pointshape = 22,
             pointsize = 1,
             fill.ind = df_vege$ste_name,
             col.ind = df_vege$ste_name,
             alpha.ind = 0.5,
             palette = "Set1",
             addEllipses = TRUE, # Concentration ellipses
             #ellipse.type = "confidence",
             title = "Individuals Plot",
             legend.title = "State",
             mean.point = FALSE) +
  ggpubr::fill_palette("Set1") +
  theme_classic2()
```


```{r}
plot_individual_all <- fviz_pca_ind(res.pca,
             geom.ind = "point", # show points only (nbut not "text")
             pointshape = 22,
             pointsize = 1,
             fill.ind = df_vege$ste_name,
             col.ind = df_vege$ste_name,
             alpha.ind = 0.5,
             palette = "Set1",
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "convex",
             title = "Individuals Plot",
             legend.title = "State",
             mean.point = FALSE) +
  ggpubr::fill_palette("Set1") +
  theme_classic2()

plot_individual_all
```


```{r}
df_vege %>% 
  count(ste_name, sort = TRUE)
```

## Graph of trace elements

```{r}
plotfviz_pca_var(res.pca, 
             col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE,
             title = "Variable Correlation Plot",
             legend.title = "Trace element\ncontribution (%) to\nDim1 and Dim2") +
  theme_classic2()
```


```{r}
var <- get_pca_var(res.pca)
var$coord
var$contrib
```


```{r}
# Total cos2 of variables on Dim.1 and Dim.2
fviz_cos2(res.pca, choice = "var", axes = 1:2)
```


```{r fig.width=5}
fviz_contrib(res.pca, choice = "var", axes = 1:2, label = TRUE)
```


# Sydney, Melbourne, Brisbane

```{r}
df_3cities <- df_vege %>% 
  filter(sua_name %in% c("Sydney", "Melbourne", "Brisbane"))

res.pca.3cities <- PCA(df_3cities[ , c("As", "Cd", "Cr", "Cu", "Mn", "Pb", "Ni", "Zn")], 
                       graph = FALSE)
```

## Eigenvalues / Varianaces

```{r}
fviz_eig(res.pca.3cities, addlabels = TRUE, title = "Scree Plot") +
  theme_classic2()
```

## Graph of individuals

```{r}
fviz_pca_ind(res.pca.3cities,
             axes = c(1, 2),
             geom.ind = "point", # show points only (nbut not "text")
             pointshape = 22,
             pointsize = 1,
             fill.ind = df_3cities$sua_name,
             col.ind = df_3cities$sua_name,
             alpha.ind = 0.5,
             palette = "Set1",
             addEllipses = TRUE, # Concentration ellipses
             #ellipse.type = "convex",
             title = "Individuals Plot",
             legend.title = "Cities",
             mean.point = FALSE) +
  ggpubr::fill_palette("Set1") +
  theme_classic2()
```


```{r}
plot_individual_3cities <- fviz_pca_ind(res.pca.3cities,
             geom.ind = "point", # show points only (nbut not "text")
             pointshape = 22,
             pointsize = 1,
             fill.ind = df_3cities$sua_name,
             col.ind = df_3cities$sua_name,
             alpha.ind = 0.5,
             palette = "Set1",
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "convex",
             title = "Individuals Plot",
             legend.title = "Cities",
             mean.point = FALSE) +
  ggpubr::fill_palette("Set1") +
  theme_classic2()

plot_individual_3cities
```


```{r}
df_3cities %>% 
  count(sua_name, sort = TRUE)
```

## Graph of trace elements

```{r}
fviz_pca_var(res.pca.3cities, 
             col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE,
             title = "Variable Correlation Plot",
             legend.title = "Trace element\ncontribution (%) to\nDim1 and Dim2"
             ) +
  theme_classic2()
```

```{r fig.width=5}
fviz_contrib(res.pca.3cities, choice = "var", axes = 1:2, label = TRUE)
```

```{r}
citation("FactoMineR")
citation("factoextra")

library(FactoMineR)
library(factoextra)
library(ggpubr)
```




